### ISSUE TITLE
Feature request - Zeroing the Z axis using a touch probe

### ISSUE THREAD

**Issue by funinthefalls** [LaserWeb/LaserWeb4#126]
Are there any plans to add code to allow using a touch probe to zero the Z axis? Estlcam has one that not only Zeros the axis but also corrects for skewed material. https://www.youtube.com/watch?v=bhZdbgM6S70

**Comment by openhardwarecoza** [comment]
4) Click dropdown again,  click zero z

On Jan 15, 2017 7:21 AM, wrote:

Zero Z
1) dropdown next to DRO
2) click probe z
3) let it probe succesfully

On Jan 15, 2017 7:19 AM, "Anthony Bolgar" <notifications@github.com> wrote:

Are there any plans to add code to allow using a touch probe to zero the Z
axis? Estlcam has one that not only Zeros the axis but also corrects for
skewed material. https://www.youtube.com/watch?v=bhZdbgM6S70

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/126>, or mute the thread

**Comment by openhardwarecoza** [comment]
Zero Z
1) dropdown next to DRO
2) click probe z
3) let it probe succesfully

On Jan 15, 2017 7:19 AM, "Anthony Bolgar" <notifications@github.com> wrote:

Are there any plans to add code to allow using a touch probe to zero the Z
axis? Estlcam has one that not only Zeros the axis but also corrects for
skewed material. https://www.youtube.com/watch?v=bhZdbgM6S70

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/126>, or mute the thread
