### ISSUE TITLE
npm start not opening correct webpage (Win10)

### ISSUE THREAD

**Issue by cprezzi** [LaserWeb/LaserWeb4#145]
When I start the dev environment with `npm start` a browser is open with url `0.0.0.0:8080` which is not working on Windows 10. Could we use localhost:8080 instead? Would that work on all supported platforms?

**Comment by jorgerobles** [comment]
Yes, will work. It's located on package.json so easy to change.

El 7 feb. 2017 11:22, "Claudio Prezzi" <notifications@github.com> escribió:

When I start the dev environment with npm start a browser is open with url
0.0.0.0:8080 which is not working on Windows 10. Could we use
localhost:8080 instead? Would that work on all supported platforms?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/145>, or mute the thread

**Comment by cprezzi** [comment]
Actually it is in webpack.congif.js and I have changed it already on my system. I just was not sure if I should push it to git.

**Comment by jorgerobles** [comment]
Yes, of course, thanks :)

**Comment by jorgerobles** [comment]
Hmm, seems trickier than I thought. Localhost wont allow remote clients to access (same lan, etc)

**Comment by openhardwarecoza** [comment]
Since the average user never has to deal with it, do we really need to autostart chrome?
The original issue, just asked that we print the IP/Port it listens on in the nodejs terminal like lw3 does

The thing is, unlike LW3, normal users wont run LW4's Webpack server at all...  We'll use webpack to pack a dist, which will pair up with lw.comms-server.  LW.comms-server can print its IP/port. 

So.... redundant?

**Comment by jorgerobles** [comment]
Well, was requested on https://github.com/LaserWeb/LaserWeb4/issues/104
I tested changing to localhost on webpack.config.js to 
` devServer: {
        contentBase: dist_path,
        inline: false,
        hot: true,
        host: 'localhost'
    },`

And seems working well enough ...but I cannot foresee any issue arising changing this.

**Comment by openhardwarecoza** [comment]
(: if its fixed its better

**Comment by jorgerobles** [comment]
@cprezzi Is it working for you with this patch?

**Comment by cprezzi** [comment]
It's working for me with only changing `devServer: { .... host: 'localhost' }`

**Comment by jorgerobles** [comment]
Perfect :)

**Comment by tbfleming** [comment]
0.0.0.0 works on my Windows 10 machines and my Linux VMs. It means bind to all addresses; it allows remote connections unlike localhost. The confusing part: 0.0.0.0 is valid for servers, not clients. Chrome has to connect to localhost or the appropriate IP address if remote.
