### ISSUE TITLE
Electron build number not updated on the top border of the app

### ISSUE THREAD

**Issue by cojarbi** [LaserWeb/LaserWeb4#180]
Its suppose to be 4.0.36

<img width="217" alt="screen shot 2017-03-01 at 3 14 44 pm" src="https://cloud.githubusercontent.com/assets/16444438/23479246/de6f497c-fe91-11e6-9e62-15c000ec4a19.png">

**Comment by openhardwarecoza** [comment]
Needs a manual edit.

**Comment by cprezzi** [comment]
I my numbering scheme with 4.0.x even correct? Or should it be 0.4.x?

**Comment by openhardwarecoza** [comment]
@lautr3k took us back to 0.4.0 with the start of the lw4 backend dev
(; LW3s bad stability seemed more like a 0.3.0 lol.

I stand by it being the 4th iteration so I'd say 4.x.x

But since both frontend, backend, and electron are seperate, it does pose
an interesting challenge of how to struct a version then

**Comment by cprezzi** [comment]
It's easy to add a command to the server for the app to query for the server version. I've planned that anyways. So we could show the app and server versions separately on the about window.

**Comment by cprezzi** [comment]
I have added the frontend and backend versions to the about tab and removed the hardcoded version number from the browser title.

**Comment by openhardwarecoza** [comment]
Thanks @jorgerobles you accidentally fixed #180 too with https://github.com/LaserWeb/LaserWeb4/issues/259 's fixes (;

![title bar](https://cloud.githubusercontent.com/assets/7695323/25093318/0abeddf6-2392-11e7-8145-31fb0c19c62c.PNG)
