### ISSUE TITLE
Machine coordinates always zero

### ISSUE THREAD

**Issue by cashbonus** [LaserWeb/LaserWeb4#493]
machine coordinates is always zero at jog or work mode no matter. SW knows coordinates and can go to XY 0, but it still displayed 0.00 mm in all three axis

**Comment by jorgerobles** [comment]
$10=0

**Comment by cashbonus** [comment]
Perfect!

**Comment by jakemauer** [comment]
For people like me who have searched for this because LaserWeb is not showing machine coordinates in the control tab, you need to enter $10=0 in the console. 

https://laserweb.yurl.ch/documentation/initial-configuration/31-grbl-1-1e/10-configure-grbl-1-1e describes the settings your machine should have.
