### ISSUE TITLE
gcode out of bounds can lead to running work halt - Elekslaser

### ISSUE THREAD

**Issue by gtu78aed87t** [LaserWeb/LaserWeb4#645]
I had it working fine until I upgraded to LaserWeb v4.1 on MacOS. 
It connects, but as soon as I go to the _"control"_ tab it disconnects with the message: _"Warning: gcode out of bounds can lead to running work halt, can lead to running work halt"_. What can I try to fix or make LaserWeb ignore this?

**Solved:** It seems a bit buggy, perhaps, but I had to load a document up front and set it within the config file's bounds. I tried to control it with no document open or gcode generated and the it would quit. Strange behaviour perhaps, but now it works fine afgain!

Edit: Another change I realized is that happened is that in under _"comms"_ port selection I now connects inder _"FTDO @ /dev/cu.usbserial-AC01XEJ5"_. It was something else before and I remember a good while ago when I first set it up that I installed some custom kext to get the Mac to communicate with the arduino controller of the machine. I think it was named something _..332_ back then, but I do not remember exactly. I don't reconize this _AC01XEJ5_ port I think, but hey it works!

**Comment by harlock999** [comment]
Which v4.1 did you download? The official binary for MacOS looks like v4.0.996
I was about to suggest to load a document first as well. This is not desirable, but a temporary workaround.

**Comment by gtu78aed87t** [comment]
I downloaded it from github as v4.1, but it shows up as v4.0.996 when I run it. So it's v4.0.996 I guess.

**Comment by cprezzi** [comment]
The latest Mac binary Version named v4.1.000 on LaserWeb4-Binaries combines Backend Version 4.1.000 and Frontend Version 4.0.999 (shown on About page after server connection).

The problem with "out of bound" is mostly caused by a offset of work coordinates to maschine coordinates which is stored into the flash memory of the crontroller. Depending on the setup, you could first run homing and then press the "set zero" button. This should save the home position as origin of the work coordinate system.
