### ISSUE TITLE
Jerky motion due to too many instructions

### ISSUE THREAD

**Issue by T-Workshop** [LaserWeb/LaserWeb4#659]
Hi,
I am dealing with an issue that I come across at different forums. When raster engraving (or raster merge) the laser becomes very jerky at higher speed (200 mm/s).
After a bit of a headache I tried generating gcode for the same image with LaserGRBL and that gcode ran fine with the same speeds and accels. After I compared the gcodes I came to the conlusion that LaserWeb is "too good" and for the M4 dynamic power it generates too many steps of the power. To simplify-where LaserGRBL steps down the S value by "1", LaserWeb steps by "0.1". 

Is there any way to reduce the "resolution" of the dynamic power mode?

Thanks
Tomas

**Comment by easytarget** [comment]
Edit:
The first answer I gave was for line cutting, not rastering. Please ignore it.

One way to reduce the resolution of raster cuts is to increase the beam size, since the cut is rendered into a grid based on that. 
- This option is perhaps mis-named, it should really be called 'beam resolution' or similar since it really means 'how big is the area my beam engraves; which is often rather larger than the actual beam size itself.
-  This depends a lot on the material you are using, and how tightly you are focusing. For a lot of engraving work you should de-focus slightly anyway, it will actually improve results.
-  My superfine laser has a best beam width of 0.08, which is fine for cutting work, but for engraving I de-focus to make the beam wider and raster at 0.2mm. This lets me use a lower speed, but the job runs faster since it is making fewer scan passes.

You can also reduce the number of grayscale colors; there are options for this in the job settings; it defaults to 256, lowering this will produce fewer intensity value changes.

If you are dithering, and using a diode laser, make sure you have the 'burn white' option enabled in the machine settings tab.

**Comment by T-Workshop** [comment]
Thanks for your reply.

Sadly this problem occurs while rastering and (please correct me if I'm wrong) there is no "segment" option there.

**Comment by easytarget** [comment]
Sorry of the initial mis-read, I've fixed the original answer
