### ISSUE TITLE
Minor UI issue?

### ISSUE THREAD

**Issue by funinthefalls** [LaserWeb/LaserWeb4#88]
In the CAM tab, the red "expand to setup operation"arrow points right to a Close X button, I have found myself accidently clicking on it when not paying attention, the arrow draws me right to the X visually.

**Comment by openhardwarecoza** [comment]
Placing them anywhere else will be hard... Shall we write it off as a user error (; @jorgerobles

**Comment by jorgerobles** [comment]
I could add a confirm nag to ensure no one closes without acknowledge oooor place the delete inside the fold, so you must unfold and then trash.

**Comment by tbfleming** [comment]
@jorgerobles please wait until much later before doing that. I frequently generate a bunch of ops then delete a bunch of ops while testing.

**Comment by tbfleming** [comment]
Actually, we'll probably won't need that once undo/redo is fully working (all the filters hooked up and undo/redo buttons added to UI to make it obvious)

**Comment by jorgerobles** [comment]
You are right. I use the rule of 3 in my work. Until a request arises 3
times a month we won't do anything ;)

El 19 dic. 2016 19:18, "Todd Fleming" <notifications@github.com> escribió:

@jorgerobles <https://github.com/jorgerobles> please wait until much later
before doing that. I frequently generate a bunch of ops then delete a bunch
of ops while testing.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/LaserWeb/LaserWeb4/issues/88#issuecomment-268037391>,
or mute the thread

**Comment by funinthefalls** [comment]
I have no problems closing this issue. Like I said it is more of an accidental close that happens because the chair<-->keyboard interface unit does not always function correctly ;)
